version: '3'
services:
  rags:
    image: ghcr.io/lmangani/rags-docker:latest
    ports:
      - '8501:8501'
    environment:
      - OPENAI_API_KEY=""
      - OPENAI_API_BASE="http://gpt4free-api:1337/v1"
  gpt4free-api: gpt4free
    image: ghcr.io/lmangani/rags-docker-gtp4free:latest
    ports:
      - '1337:1337'
    command: api
  gpt4free-gui:
    image: ghcr.io/lmangani/rags-docker-gtp4free:latest
    ports:
      - '1338:80'
    command: gui
