on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gpt4free
  
jobs:
  releases-matrix:
    name: Release Image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Get gpt4free
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'xtekky'
        repository: 'gpt4free'
    - name: Log in to the Container registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./gpt4free
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
